// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfnxpuduwpehyhfykliw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbnhwdWR1d3BlaHloZnlrbGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzE4MDcsImV4cCI6MjA1OTI0NzgwN30.q9Wjrph3sfwapI6ITImtm7eOlEuuNYwql7d62cf0WMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);